/* tslint:disable */
// @ts-nocheck
const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');
const path = require('path');
require('dotenv').config({
  path: path.resolve(__dirname, '../environments/.env'),
});

// Providing path to the `environments` directory
const envDirectory = './src/environments';
const environment = argv.environment;

const isProduction = environment === 'prod';
const targetPath = isProduction
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts';

const writeFileUsingFS = (targetPath, environmentFileContent) => {
  writeFile(targetPath, environmentFileContent, (err) => {
    if (err) console.log(err);
    if (environmentFileContent !== '')
      console.log(`wrote variables to ${targetPath}`);
  });
};

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

//creates the `environment.prod.ts` and `environment.ts` file if it does not exist
writeFileUsingFS('./src/environments/environment.prod.ts', '');
writeFileUsingFS('./src/environments/environment.ts', '');

//actual content to be compiled dynamically and pasted into respective environment files
const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: ${isProduction},
    firebase: {
      apiKey: '${process.env.FIREBASE_API_KEY}',
      authDomain: "angular-grocery-project-a2912.firebaseapp.com",
      projectId: "angular-grocery-project-a2912",
      storageBucket: "angular-grocery-project-a2912.appspot.com",
      messagingSenderId: "481843992186",
      appId: "1:481843992186:web:1cba21496876d8e62c8dc3"
    }
  };
`;

writeFileUsingFS(targetPath, environmentFileContent); // appending data into the target file

/* tslint:enable */
